name: macOS 10.15

on:
  pull_request:
    branches: [ main ]

jobs:
  hardware:
    name: Hardware
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: pip2 install future
      - run: brew install --cask kicad
      - run: ./blocks/audio-in-daisy/build.py
      - run: ./blocks/audio-out-daisy/build.py
      - run: ./blocks/button/build.py
      - run: ./blocks/cv-in/build.py
      - run: ./blocks/gate-in/build.py
      - run: ./blocks/gate-out/build.py
      - run: ./blocks/led/build.py
      - run: ./blocks/led-bi/build.py
      - run: ./blocks/multiplexer/build.py
      - run: ./blocks/pot/build.py
      - run: ./blocks/power-bus/build.py
      - run: ./blocks/regulator-daisy/build.py
      - run: ./blocks/slider/build.py
      - run: ./blocks/switch/build.py
      - run: ./blocks/trim/build.py
      - run: ./blocks/kits/stats.py
      - run: ./blocks/kits/build.py

  software:
    name: Software
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: brew install armmbed/formulae/arm-none-eabi-gcc
      - run: brew install ninja
      - run: brew install cairo libffi
      - run: brew install dfu-util
      - run: pip3 install cairosvg cairocffi
      - run: pip3 install ezdxf
      - run: mkdir -p ~/Library/Fonts
      - run: cp include/erb/vcvrack/design/d-din/*.otf ~/Library/Fonts
      - run: cp include/erb/vcvrack/design/indie-flower/*.ttf ~/Library/Fonts
      - run: python3 blocks/test/configure.py
      - run: python3 blocks/test/build.py
      - run: python3 samples/drop/configure.py
      - run: python3 samples/drop/build.py
      - run: python3 samples/drop/build.py --erb-target vcvrack

  unit_tests:
    name: Unit Tests
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: brew install ninja
      - run: python3 test/unit/configure.py
      - run: python3 test/unit/build.py
      - run: python3 test/unit/run.py

  erbb_tests:
    name: Erbb/Erbui Tests
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: brew install cairo libffi
      - run: pip3 install cairosvg cairocffi
      - run: pip3 install ezdxf
      - run: pip3 install coverage
      - run: mkdir -p ~/Library/Fonts
      - run: cp include/erb/vcvrack/design/d-din/*.otf ~/Library/Fonts
      - run: cp include/erb/vcvrack/design/indie-flower/*.ttf ~/Library/Fonts
      - run: python3 build-system/test.py
      - run: python3 build-system/cover.py
      - run: python3 test/vcvrack/configure.py
      - run: python3 test/vcvrack/build.py
